[2025-06-15 13:38:20] [INFO    ] discord.client: logging in using static token
[2025-06-15 13:38:21] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 89cffde983ee1c30d48a7f920401499d).
[2025-06-15 17:01:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-15 17:22:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-15 19:12:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-15 19:55:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-15 22:24:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 01:59:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 04:19:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 05:57:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 07:40:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 08:58:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 11:13:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 14:15:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 16:42:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 17:20:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 18:29:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 19:17:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 21:47:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 23:12:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 23:23:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-16 23:46:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 02:48:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 06:05:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 08:01:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 08:16:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 08:32:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 09:11:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 09:58:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 10:25:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 10:34:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 12:10:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 12:24:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 12:59:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 14:37:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 14:48:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 15:43:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 16:11:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 18:20:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 20:03:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-17 22:18:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 02:17:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 05:48:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 07:24:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 09:45:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 13:39:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 13:53:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 15:08:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 15:18:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 15:22:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 17:27:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 18:54:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 20:19:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 21:14:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 21:18:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 21:29:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 22:18:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-18 23:00:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 01:03:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 01:29:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 02:42:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 03:56:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 05:03:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 06:15:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 07:54:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 08:24:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 08:38:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 10:09:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 11:24:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 11:34:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 11:57:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 12:40:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 12:55:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 14:26:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 15:05:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 17:36:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-19 20:25:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 00:05:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 00:13:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 00:19:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 02:04:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 03:12:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 05:39:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 07:23:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 11:19:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 13:00:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 14:43:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 17:05:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 19:24:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 20:25:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-20 21:54:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 01:39:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 03:37:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 06:50:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 09:26:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 11:10:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 14:05:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 17:57:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 19:56:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-21 22:44:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 01:34:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 03:07:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 04:52:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 08:03:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 09:39:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 12:50:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 15:08:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 16:27:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 16:43:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 18:49:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 19:05:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 22:43:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-22 23:09:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 00:10:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 01:54:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 03:49:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 04:06:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 05:23:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 06:45:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 07:41:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 09:48:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 11:03:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 11:49:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 14:53:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 16:05:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 17:00:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 17:19:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 17:35:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 17:36:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 19:48:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 21:47:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-23 23:35:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 00:58:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 03:25:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 04:57:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 07:52:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 09:01:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 10:26:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 11:38:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 12:51:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 15:12:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 15:39:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 15:51:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 16:18:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 17:46:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 19:05:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 19:13:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-24 22:47:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 00:30:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 03:08:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 06:10:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 08:43:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 09:35:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 10:18:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 11:59:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 13:15:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 13:42:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 14:43:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 17:01:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 17:19:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 21:06:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-25 22:45:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 01:51:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 03:55:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 07:34:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 10:03:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 10:07:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 10:09:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 10:22:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 10:25:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 11:50:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 12:17:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 13:27:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 15:06:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 15:50:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 17:54:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 21:51:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-26 22:50:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 02:05:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 03:05:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 06:22:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 09:14:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 12:58:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 14:15:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 16:43:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 18:34:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 20:27:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-27 23:40:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 01:58:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 05:00:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 08:17:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 10:52:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 12:19:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 12:59:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 14:02:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 15:23:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 18:36:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 19:42:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 22:52:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-28 23:32:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 01:45:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 05:13:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 07:19:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 07:26:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 08:43:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 11:18:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 13:15:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 17:08:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 18:45:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-29 20:54:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 00:45:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 04:22:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 05:06:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 06:34:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 06:40:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 08:15:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 08:36:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 09:28:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 09:56:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 10:21:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 12:38:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 15:09:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 15:38:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 16:23:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 19:07:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 19:20:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-06-30 23:16:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 01:25:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 01:48:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 05:23:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 07:05:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 07:45:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 08:14:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 08:46:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 10:49:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 10:54:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 10:54:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 12:16:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 12:39:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 13:07:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 14:24:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 14:44:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 16:06:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 16:10:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 16:45:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 17:41:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 17:59:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 19:36:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 21:04:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-01 22:38:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 00:42:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 02:40:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 05:00:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 06:48:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 09:10:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 09:42:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 10:52:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 11:21:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 12:34:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 14:40:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 15:56:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 16:07:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 16:20:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 16:37:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 18:34:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 21:02:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-02 21:14:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 00:16:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 00:32:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 01:31:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 01:59:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 04:56:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 07:35:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 09:24:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 09:54:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 09:55:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 10:04:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 13:51:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 14:16:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 14:38:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 14:52:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 15:26:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 15:41:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 16:44:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 16:59:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 19:36:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 19:52:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 21:43:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 22:07:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 22:14:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-03 22:41:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 01:04:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 01:40:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 01:54:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 02:43:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 03:03:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 03:25:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 03:43:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 04:41:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 07:27:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 09:00:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 09:20:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 09:35:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 10:00:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 11:31:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 11:42:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 11:49:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 12:10:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 13:24:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 13:40:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 14:41:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 16:04:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 16:32:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 16:53:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 18:38:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 19:32:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 20:12:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 20:39:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 21:30:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-04 23:10:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 00:04:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 00:29:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 00:57:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 01:17:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 02:59:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 04:20:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 04:46:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 05:16:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 05:48:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 07:31:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 08:08:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 10:10:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 11:39:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 13:07:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 13:27:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 15:38:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 16:38:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 18:40:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 18:53:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 19:32:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 19:59:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 22:31:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 22:52:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 23:19:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-05 23:57:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 00:13:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 01:01:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 02:08:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 02:31:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 02:55:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 03:20:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 04:44:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 06:14:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 07:12:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 09:29:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 11:04:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 11:56:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 13:31:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 13:58:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 15:23:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 16:04:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 16:24:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 18:13:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 18:40:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 19:47:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 21:36:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-06 22:45:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 00:23:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 02:15:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 02:39:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 04:29:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 04:49:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 05:02:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 05:25:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 07:41:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 08:03:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 09:16:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 09:34:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 10:05:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 10:26:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 11:07:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 12:05:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 12:36:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 14:55:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 18:35:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 19:53:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 19:59:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 20:18:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 21:29:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 22:46:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-07 23:44:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 00:04:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 01:18:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 03:51:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 04:36:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 04:45:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 04:58:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 07:57:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 09:28:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 12:59:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 13:15:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 14:50:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 15:01:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 17:33:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 18:12:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 19:08:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 19:13:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 19:15:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 19:44:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-08 22:22:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-09 01:33:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-09 02:08:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-09 05:51:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 89cffde983ee1c30d48a7f920401499d.
[2025-07-09 08:02:02] [ERROR   ] discord.client: Attempting a reconnect in 1.71s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-09 08:02:28] [ERROR   ] discord.client: Attempting a reconnect in 2.74s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-09 08:02:53] [ERROR   ] discord.client: Attempting a reconnect in 2.62s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-09 08:03:13] [ERROR   ] discord.client: Attempting a reconnect in 10.59s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-09 08:03:34] [ERROR   ] discord.client: Attempting a reconnect in 6.91s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-09 08:03:46] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-09 08:03:51] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ed6c7583d6421ea25b5b8a214f4e52f6).
[2025-07-09 08:51:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 09:45:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 10:12:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 11:36:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 15:24:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 15:50:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 15:55:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 18:21:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 19:41:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 21:04:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-09 23:20:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 02:33:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 02:38:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 02:55:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 06:01:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 06:06:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 09:35:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 10:52:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 11:27:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 12:12:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 13:14:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 14:21:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 14:23:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 17:34:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 21:28:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-10 22:29:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 00:01:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 01:05:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 03:11:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 04:19:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 06:04:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 08:35:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 09:15:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 09:22:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 09:32:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 11:04:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 11:23:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 12:44:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 15:12:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 15:38:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 18:08:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 19:53:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 20:02:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-11 21:36:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 00:35:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 03:09:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 06:25:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 09:55:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 11:02:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 13:52:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 15:55:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 16:22:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 16:45:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 18:35:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 19:02:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-12 22:32:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 02:08:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 04:41:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 05:45:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 06:15:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 06:45:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 07:56:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 09:04:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 11:06:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 13:13:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 14:45:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 16:27:29] [ERROR   ] discord.client: Attempting a reconnect in 1.35s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-13 16:27:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 19:07:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-13 22:46:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 00:57:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 04:35:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 05:10:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 06:00:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 07:37:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 09:26:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 09:39:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 09:41:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 10:18:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 12:54:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 13:36:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 15:44:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 17:31:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 17:44:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 18:01:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 19:54:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 20:57:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-14 23:03:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 00:29:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 01:49:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 04:05:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 07:06:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 08:08:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 09:15:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 09:17:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 09:48:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 10:41:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 12:34:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 14:27:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 16:49:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 17:05:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 20:39:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-15 21:21:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 01:01:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 02:45:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 03:44:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 05:50:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 08:22:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 08:53:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 09:21:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 09:31:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 09:49:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 10:42:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 14:11:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 14:13:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 15:47:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 16:39:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 17:14:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 17:40:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 19:15:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-16 21:38:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 01:28:55] [ERROR   ] discord.client: Attempting a reconnect in 1.46s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 738, in _connect_and_send_request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client_reqrep.py", line 1141, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/streams.py", line 672, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-17 01:28:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 01:49:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 04:10:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 06:47:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 08:14:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 09:29:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 09:31:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 09:41:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 09:42:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 10:05:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 11:04:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 11:20:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 11:22:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 15:02:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 16:04:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 17:25:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 21:08:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-17 23:36:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 02:35:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 04:31:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 07:57:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 09:44:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 09:54:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 10:41:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 11:59:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 13:25:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 14:27:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 14:28:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 16:17:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 18:31:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 18:32:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 21:52:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-18 23:51:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 00:08:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 00:36:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 01:39:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 04:17:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 04:39:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 08:24:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 11:38:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 12:31:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 14:31:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 17:34:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 21:24:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 21:39:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 22:23:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 23:01:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-19 23:37:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 01:48:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 02:58:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 05:00:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 05:21:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 07:20:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 08:28:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 08:55:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 09:39:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 12:45:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 14:46:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 15:08:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 15:59:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 17:40:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 21:37:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 22:28:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 23:05:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-20 23:47:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 01:13:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 04:31:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 08:23:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 09:41:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 09:47:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 12:20:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 13:32:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 14:39:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 14:49:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 15:49:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 17:01:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 17:32:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 17:36:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-21 20:44:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 00:22:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 01:58:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 05:27:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 08:07:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 08:30:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 10:18:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 10:44:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 11:10:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 11:37:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 13:22:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 16:13:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 16:29:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 16:58:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 18:26:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 21:46:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-22 23:45:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 01:07:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 04:09:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 04:32:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 05:52:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 07:03:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 09:16:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 09:26:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 10:22:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 12:49:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 13:37:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 15:03:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 17:03:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 17:05:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 17:12:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 18:38:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 19:17:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 20:01:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 20:17:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 20:30:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 23:17:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-23 23:22:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-24 00:52:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed6c7583d6421ea25b5b8a214f4e52f6.
[2025-07-24 02:42:22] [ERROR   ] discord.client: Attempting a reconnect in 0.33s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-24 02:42:26] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-24 02:42:31] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 08e6d32e4f3f367cdc39c1df2789ebaf).
[2025-07-24 04:08:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 08e6d32e4f3f367cdc39c1df2789ebaf.
[2025-07-24 04:13:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 08e6d32e4f3f367cdc39c1df2789ebaf.
[2025-07-24 05:54:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 08e6d32e4f3f367cdc39c1df2789ebaf.
[2025-07-24 06:27:21] [ERROR   ] discord.client: Attempting a reconnect in 0.88s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-24 06:27:53] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-24 06:27:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 00b8dd7286fb3ccf2c818833393f9d9a).
[2025-07-24 06:40:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 06:41:31] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 07:26:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 10:04:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 11:58:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 13:05:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 14:08:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 15:20:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 16:23:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 16:58:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 17:41:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 18:06:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 18:40:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 19:10:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 19:12:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 19:38:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 19:45:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 21:06:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-24 22:32:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 01:09:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 05:03:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 06:52:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 08:54:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 09:00:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 09:07:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 09:22:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 11:02:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 12:53:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 13:00:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 13:12:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 14:34:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 15:14:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 17:24:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 18:12:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 20:53:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 21:15:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 23:15:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-25 23:50:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-26 01:03:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 00b8dd7286fb3ccf2c818833393f9d9a.
[2025-07-26 02:40:06] [ERROR   ] discord.client: Attempting a reconnect in 0.33s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-26 02:40:31] [ERROR   ] discord.client: Attempting a reconnect in 1.98s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-26 02:40:58] [ERROR   ] discord.client: Attempting a reconnect in 3.04s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-26 02:41:16] [ERROR   ] discord.client: Attempting a reconnect in 6.35s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-26 02:41:32] [ERROR   ] discord.client: Attempting a reconnect in 29.96s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1376, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1013, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1044, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1382, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
[2025-07-26 02:42:02] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-26 02:42:08] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d17a3ff14e31c267058d1167d4ddd758).
[2025-07-26 04:49:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 06:01:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 06:56:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 10:17:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 12:17:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 15:35:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 16:58:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 18:54:56] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 22:17:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-26 22:51:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 00:52:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 03:59:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 07:56:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 09:18:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 11:15:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 11:20:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 14:07:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 16:05:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 16:59:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 17:33:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 18:13:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 19:00:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 20:17:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 20:24:20] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 21:01:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-27 21:47:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 00:01:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 02:37:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 04:01:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 06:35:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 08:35:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 09:16:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 10:23:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 10:23:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 10:51:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 11:08:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 14:13:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 15:34:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 17:27:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 18:24:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 18:36:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 21:54:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-28 22:36:29] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d17a3ff14e31c267058d1167d4ddd758.
[2025-07-29 01:19:31] [ERROR   ] discord.client: Attempting a reconnect in 0.61s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-29 01:20:02] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-29 01:20:08] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d959546c34cc37571e1f4f2ea559e549).
[2025-07-29 04:06:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d959546c34cc37571e1f4f2ea559e549.
[2025-07-29 04:29:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session d959546c34cc37571e1f4f2ea559e549.
[2025-07-29 04:34:51] [ERROR   ] discord.client: Attempting a reconnect in 0.49s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-29 04:35:07] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-29 04:35:12] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 981a869e81c2ec8f67f8ddf1c26ea1dc).
[2025-07-29 04:55:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 07:34:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 09:02:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 09:05:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 12:37:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 13:42:18] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 14:06:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 16:11:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 18:50:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 20:14:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-29 23:06:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 981a869e81c2ec8f67f8ddf1c26ea1dc.
[2025-07-30 01:17:33] [ERROR   ] discord.client: Attempting a reconnect in 0.98s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-30 01:18:34] [ERROR   ] discord.client: Attempting a reconnect in 2.59s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-30 01:19:36] [ERROR   ] discord.client: Attempting a reconnect in 3.70s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-30 01:19:48] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-30 01:19:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 17443eed8718b18344a9e1e122d1f9a9).
[2025-07-30 02:14:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 17443eed8718b18344a9e1e122d1f9a9.
[2025-07-30 02:47:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 17443eed8718b18344a9e1e122d1f9a9.
[2025-07-30 04:05:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 17443eed8718b18344a9e1e122d1f9a9.
[2025-07-30 04:36:14] [ERROR   ] discord.client: Attempting a reconnect in 1.47s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-30 04:37:15] [ERROR   ] discord.client: Attempting a reconnect in 2.63s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-30 04:38:18] [ERROR   ] discord.client: Attempting a reconnect in 6.32s
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1036, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 760, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 715, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 561, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1074, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1133, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/impl.py", line 87, in start_connection
    sock, _, _ = await _staggered.staggered_race(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 165, in staggered_race
    done = await _wait_one(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohappyeyeballs/_staggered.py", line 46, in _wait_one
    return await wait_next
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
[2025-07-30 04:38:28] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-07-30 04:38:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5873dd963246ccff36d44976a12c589a).
[2025-07-30 07:04:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5873dd963246ccff36d44976a12c589a.
[2025-07-30 08:27:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5873dd963246ccff36d44976a12c589a.
[2025-07-30 09:32:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5873dd963246ccff36d44976a12c589a.
[2025-07-30 10:09:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5873dd963246ccff36d44976a12c589a.
[2025-07-30 11:53:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 5873dd963246ccff36d44976a12c589a.
Killed
